export const language = {
  ua: {
    name: "Ua",
    project: "Мої проекти",
    services: "Мої послуги",
    contact: "Контакти",
    number: "Мій номер телефону:",
    projectsTitle: "Мої проекти",
    servicesTitle: "Мої послуги",
    myServicesContentTitle1: "Виконую робочу документацію наступних розділів:",
    myServicesContentTitle2:
      "Також виконую швидко і якісно роботи по проектуванню стадій:",
    myServicesItemText1: "АР (архітектурні рішення);",
    myServicesItemText2: "ТХ (технологічні рішення);",
    myServicesItemText3: "ГП (генеральний план);",
    myServicesItemText4: "КМ (конструкції металеві);",
    myServicesItemText5: "КБ (конструкції залізобетонні);",
    myServicesItemText6: "ВК (водопровід, каналізація);",
    myServicesItemText7: "ПОБ (план організації будівництва);",
    myServicesItemText8: "ПП (попереднє проектування, концепція будівництва):",
    myServicesItemText9: "ЕП (ескізний проект);",
    myServicesItemText10: "П (проектування);",
    myServicesItemText11: "РП (робочий проект);",
    myServicesItemText12: "РД (робоча документація).",
  },
  en: {
    name: "EN",
    project: "My Projects",
    services: "My services",
    contact: "Contact",
    number: "My phone number:",
    projectsTitle: "My projects",
    servicesTitle: "My services",
    myServicesContentTitle1:
      "I am preparing working documentation for the following sections:",
    myServicesContentTitle2:
      "I also perform fast and high-quality work on stage design:",
    myServicesItemText1: "AR (architectural solutions);",
    myServicesItemText2: "TX (technological solutions);",
    myServicesItemText3: "GP (general plan);",
    myServicesItemText4: "KM (metal structures);",
    myServicesItemText5: "KB (reinforced concrete structures);",
    myServicesItemText6: "VK(water supply, sewage);",
    myServicesItemText7: "POB (construction organization plan);",
    myServicesItemText8: "PP (preliminary design, construction concept):",
    myServicesItemText9: "EP (draft design);",
    myServicesItemText10: "P (project);",
    myServicesItemText11: "RP (working design);",
    myServicesItemText12: "RD (working documentation).",
  },
};
